name: CI/CD for Spring Boot to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs
        
    - name: Set up Docker
      uses: actions/setup-docker@v2
      with:
        dockerfile: Dockerfile

    - name: Build Docker image
      run: docker build -f .  -t your-docker-username/your-image-name:latest

    - name: Log in to Docker Hub
      run: docker login -u symjaehyun -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: docker push your-docker-username/your-image-name:latest        